routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::group(['middleware' => ['web', 'cekLevel:1']], function(){
	// KATEGORI
	Route::get('kategori/data', 'coKategori@listData')->name('kategori.data');
	Route::resource('kategori', 'coKategori');
	Route::get('kategori', 'coKategori@index')->name('kategori');
	// PRODUK
	Route::get('produk/data', 'coProduk@listData')->name('produk.data');
	Route::post('produk/hapus', 'coProduk@deleteSelected')->name('produk.hapus');
	Route::post('produk/cetak', 'coProduk@printBarcode')->name('produk.cetak');
	Route::resource('produk', 'coProduk');
	Route::get('produk', 'coProduk@index')->name('produk');
});

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/produk', 'coKategori@index')->name('produk');
// Route::get('/member', 'coKategori@index')->name('member');
// Route::get('/supplier', 'coKategori@index')->name('supplier');
// Route::get('/pengeluaran', 'coKategori@index')->name('pengeluaran');
// Route::get('/user', 'coKategori@index')->name('user');
// Route::get('/penjualan', 'coKategori@index')->name('penjualan');
// Route::get('/pembelian', 'coKategori@index')->name('pembelian');
// Route::get('/laporan', 'coKategori@index')->name('laporan');
// Route::get('/setting', 'coKategori@index')->name('setting');
// Route::get('/transaksi', 'coKategori@index')->name('transaksi');

resources/views/kategori/form_kategori.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form class="form-horizontal" id="frmKategori" data-toggle="validator" method="POST">
				{{ csrf_field() }} {{ method_field('POST') }}
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span></button>
					<h3 class="modal-title"></h3>
				</div>
				<div class="modal-body">
					<input type="hidden" name="id" id="id">
					<div class="form-group">
						<label for="nama" class="col-md-3 control-label">Nama Produk</label>
						<div class="col-md-6">
							<input type="text" name="nama" id="nama" class="form-control" autofocus required>
							<span class="help-block with-errors"></span>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> SIMPAN</button>
					<button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> BATAL</button>
				</div>
			</form>
		</div>
	</div>
</div>

resources/views/kategori/index_kategori.blade.php
@extends('layouts.app')

@section('title')
	Daftar Kategori
@endsection

@section('breadcrumb')
	<li class="active">Kategori</li>
@endsection

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<div class="box-header">
					<a href="#" onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
				</div>
				<div class="box-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th width="30">No</th>
								<th>Nama Kategori</th>
								<th width="100">Aksi</th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	@include('kategori.form_kategori')
	<meta name="_token" content="{{ csrf_token() }}" />
@endsection

@section('script')
	<script type="text/javascript">
		var table, save_method;
		$(function(){
			table = $('.table').DataTable({
				"processing": true,
				"ajax": {
					"url": "{{ route('kategori.data') }}",
					"type": "GET"
				}
			});

			$('#modal-form form').validator().on('submit', function(e){
				$.ajaxSetup({
			        headers: {
			            'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
			        }
			    });
			    
				if(!e.isDefaultPrevented()){
					var id = $('#id').val();
					if(save_method == "add"){
						url = "{{ route('kategori.store') }}";
						type = "POST";
					}else{
						url = "kategori/"+id;
						type = "PUT";
					}

					$.ajax({
						url: url,
						type: type,
						data: $('#modal-form form').serialize(),
						success: function(data){
							table.ajax.reload();
							$('#modal-form').modal('hide');
						},
						error: function(){
							alert("Tidak dapat menyimpan data!");
						}
					});
					return false;
				}
			});
		});

		function addForm(){
			save_method = "add";
			$('input[name=method]').val('POST');
			$('#modal-form').modal('show');
			$('#frmKategori')[0].reset();
			$('.modal-title').text('Tambah Kategori');
		}

		function editForm(id){
			save_method = "edit";
			$('input[name=method]').val('PATCH');
			$('#frmKategori')[0].reset();
			$.ajax({
				url: "kategori/"+id+"/edit",
				type: "GET",
				dataType: "JSON",
				success: function(data){
					$('#modal-form').modal('show');
					$('.modal-title').text('Edit Kategori');
					$('#id').val(data.id_kategori);
					$('#nama').val(data.nama_kategori);
				},
				error: function(){
					alert("Tidak dapat menampilkan data!");
				}
			});
		}

		function deleteData(id){
			if(confirm("Apakah yakin data akan dihapus ?")){
				$.ajaxSetup({
			        headers: {
			            'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
			        }
			    });

				$.ajax({
					url: "kategori/"+id,
					type: "DELETE",
					data: {'_token' : $('meta[name=csrf-token]').attr('content')},
					success: function(data){
						table.ajax.reload();
					},
					error: function(){
						alert("Tidak dapat menghapus data!");
					}
				});
			}
		}
	</script>
@endsection